spring:
  config:
    import: classpath:application-secret.yml

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  devtools:
    restart:
      enabled: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081
  address: 0.0.0.0
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

# AI 서비스 설정
ai:
  workflow:
    url: http://localhost:8000
  precedents-analysis:
    url: http://localhost:8000
  engine:
    base-url: http://localhost:8000
    timeout: 30000
    retry-count: 3

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org:
      springframework:
        security: DEBUG
        web: INFO
        web.client: WARN

